create table "public"."Poll" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "end_at" timestamp with time zone
);


alter table "public"."Poll" enable row level security;

create table "public"."Vote" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "restaurant_id" bigint,
    "vote_count" bigint default '0'::bigint,
    "poll_id" bigint
);


alter table "public"."Vote" enable row level security;

alter table "public"."Restaurant" drop column "vote_count";

CREATE UNIQUE INDEX "Poll_pkey" ON public."Poll" USING btree (id);

CREATE UNIQUE INDEX "Vote_pkey" ON public."Vote" USING btree (id);

alter table "public"."Poll" add constraint "Poll_pkey" PRIMARY KEY using index "Poll_pkey";

alter table "public"."Vote" add constraint "Vote_pkey" PRIMARY KEY using index "Vote_pkey";

grant delete on table "public"."Poll" to "anon";

grant insert on table "public"."Poll" to "anon";

grant references on table "public"."Poll" to "anon";

grant select on table "public"."Poll" to "anon";

grant trigger on table "public"."Poll" to "anon";

grant truncate on table "public"."Poll" to "anon";

grant update on table "public"."Poll" to "anon";

grant delete on table "public"."Poll" to "authenticated";

grant insert on table "public"."Poll" to "authenticated";

grant references on table "public"."Poll" to "authenticated";

grant select on table "public"."Poll" to "authenticated";

grant trigger on table "public"."Poll" to "authenticated";

grant truncate on table "public"."Poll" to "authenticated";

grant update on table "public"."Poll" to "authenticated";

grant delete on table "public"."Poll" to "service_role";

grant insert on table "public"."Poll" to "service_role";

grant references on table "public"."Poll" to "service_role";

grant select on table "public"."Poll" to "service_role";

grant trigger on table "public"."Poll" to "service_role";

grant truncate on table "public"."Poll" to "service_role";

grant update on table "public"."Poll" to "service_role";

grant delete on table "public"."Vote" to "anon";

grant insert on table "public"."Vote" to "anon";

grant references on table "public"."Vote" to "anon";

grant select on table "public"."Vote" to "anon";

grant trigger on table "public"."Vote" to "anon";

grant truncate on table "public"."Vote" to "anon";

grant update on table "public"."Vote" to "anon";

grant delete on table "public"."Vote" to "authenticated";

grant insert on table "public"."Vote" to "authenticated";

grant references on table "public"."Vote" to "authenticated";

grant select on table "public"."Vote" to "authenticated";

grant trigger on table "public"."Vote" to "authenticated";

grant truncate on table "public"."Vote" to "authenticated";

grant update on table "public"."Vote" to "authenticated";

grant delete on table "public"."Vote" to "service_role";

grant insert on table "public"."Vote" to "service_role";

grant references on table "public"."Vote" to "service_role";

grant select on table "public"."Vote" to "service_role";

grant trigger on table "public"."Vote" to "service_role";

grant truncate on table "public"."Vote" to "service_role";

grant update on table "public"."Vote" to "service_role";


