create table "public"."Restaurant" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying,
    "url" character varying,
    "vote_count" bigint
);


alter table "public"."Restaurant" enable row level security;

CREATE UNIQUE INDEX "Restaurant_pkey" ON public."Restaurant" USING btree (id);

alter table "public"."Restaurant" add constraint "Restaurant_pkey" PRIMARY KEY using index "Restaurant_pkey";

grant delete on table "public"."Restaurant" to "anon";

grant insert on table "public"."Restaurant" to "anon";

grant references on table "public"."Restaurant" to "anon";

grant select on table "public"."Restaurant" to "anon";

grant trigger on table "public"."Restaurant" to "anon";

grant truncate on table "public"."Restaurant" to "anon";

grant update on table "public"."Restaurant" to "anon";

grant delete on table "public"."Restaurant" to "authenticated";

grant insert on table "public"."Restaurant" to "authenticated";

grant references on table "public"."Restaurant" to "authenticated";

grant select on table "public"."Restaurant" to "authenticated";

grant trigger on table "public"."Restaurant" to "authenticated";

grant truncate on table "public"."Restaurant" to "authenticated";

grant update on table "public"."Restaurant" to "authenticated";

grant delete on table "public"."Restaurant" to "service_role";

grant insert on table "public"."Restaurant" to "service_role";

grant references on table "public"."Restaurant" to "service_role";

grant select on table "public"."Restaurant" to "service_role";

grant trigger on table "public"."Restaurant" to "service_role";

grant truncate on table "public"."Restaurant" to "service_role";

grant update on table "public"."Restaurant" to "service_role";


